services:
  - type: web
    name: control-gastos-dashboard
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server"
    plan: free
    autoDeploy: true
